#!/usr/bin/env swift

// Traces "sonar" in Unbounded Bold into Sources/Sonar/shared/brand/Wordmark.swift, so the app ships a ~2 KB shape
// instead of a 778 KB font. Unbounded is © The Unbounded Project Authors, SIL Open Font License 1.1.
// Run: ./icon/make-wordmark.swift path/to/Unbounded[wght].ttf
//   (font: https://github.com/google/fonts/tree/main/ofl/unbounded)
import CoreText
import Foundation

let fontURL = URL(fileURLWithPath: CommandLine.arguments[1])
let descriptors = CTFontManagerCreateFontDescriptorsFromURL(fontURL as CFURL) as! [CTFontDescriptor]
let wght = 0x7767_6874  // 'wght'
let bold = CTFontDescriptorCreateCopyWithAttributes(
    descriptors[0], [kCTFontVariationAttribute: [wght: 700]] as CFDictionary)
let font = CTFontCreateWithFontDescriptor(bold, 100, nil)

let line = CTLineCreateWithAttributedString(NSAttributedString(string: "sonar", attributes: [.init(kCTFontAttributeName as String): font]))
let path = CGMutablePath()
for run in CTLineGetGlyphRuns(line) as! [CTRun] {
    let count = CTRunGetGlyphCount(run)
    var glyphs = [CGGlyph](repeating: 0, count: count)
    var positions = [CGPoint](repeating: .zero, count: count)
    CTRunGetGlyphs(run, CFRange(), &glyphs)
    CTRunGetPositions(run, CFRange(), &positions)
    for (g, p) in zip(glyphs, positions) {
        if let glyphPath = CTFontCreatePathForGlyph(font, g, nil) {
            path.addPath(glyphPath, transform: CGAffineTransform(translationX: p.x, y: p.y))
        }
    }
}

// Normalize to a 0...1 box height, flipped for SwiftUI's top-left origin.
let box = path.boundingBoxOfPath
let scale = 1 / box.height
func pt(_ p: CGPoint) -> String {
    String(format: "p(%.4f, %.4f)", (p.x - box.minX) * scale, (box.maxY - p.y) * scale)
}
var lines: [String] = []
path.applyWithBlock { element in
    let e = element.pointee
    switch e.type {
    case .moveToPoint: lines.append("path.move(to: \(pt(e.points[0])))")
    case .addLineToPoint: lines.append("path.addLine(to: \(pt(e.points[0])))")
    case .addQuadCurveToPoint: lines.append("path.addQuadCurve(to: \(pt(e.points[1])), control: \(pt(e.points[0])))")
    case .addCurveToPoint:
        lines.append("path.addCurve(to: \(pt(e.points[2])), control1: \(pt(e.points[0])), control2: \(pt(e.points[1])))")
    case .closeSubpath: lines.append("path.closeSubpath()")
    @unknown default: break
    }
}

let aspect = box.width / box.height
let swift = """
    // Generated by icon/make-wordmark.swift from Unbounded Bold (SIL Open Font License 1.1). Don't edit by hand.
    import SwiftUI

    /// "sonar" in Unbounded Bold as a shape. Aspect ratio \(String(format: "%.4f", aspect)) : 1.
    struct Wordmark: Shape {
        static let aspectRatio: CGFloat = \(String(format: "%.4f", aspect))

        func path(in rect: CGRect) -> Path {
            let h = rect.height
            func p(_ x: CGFloat, _ y: CGFloat) -> CGPoint { CGPoint(x: rect.minX + x * h, y: rect.minY + y * h) }
            var path = Path()
            \(lines.joined(separator: "\n        "))
            return path
        }
    }

    """
let out = URL(fileURLWithPath: #filePath).deletingLastPathComponent().deletingLastPathComponent()
    .appendingPathComponent("Sources/Sonar/shared/brand/Wordmark.swift")
try! swift.write(to: out, atomically: true, encoding: .utf8)
print("Wrote \(out.path) (\(lines.count) path elements)")
